export const GET_ALL_NOTES = 'GET_ALL_NOTES';
export const SET_ALL_NOTES = 'SET_ALL_NOTES';
export const REMOVE_ITEM = 'REMOVE_ITEM';

export const SET_PAGE_NUMBER = 'SET_PAGE_NUMBER';

export const NOTES_LOADING_STATUS = 'NOTES_LOADING_STATUS';
